### ISSUE TITLE
Mongo "Join" collections

### ISSUE THREAD

**Issue by mbouclas** [strongloop/loopback-example-relations#15]
I don't know if this is even possible via relationships, but i have to ask.
Document in collection "articles" has a structure like so :

```
{
title : 'A title',
categories : [ObjectId("563732b5abb68880215dcfe4"),ObjectId("563732b5abb68880215dcfd5")]
}
```

Then document in collection categories has a structure like so :

```
{
    "_id" : ObjectId("563732b5abb68880215dcfe4"),
    "category" : "A category",
    "description" : "",
    "orderBy" : 0,
    "settings" : {},
    "active" : true,
    "thumb" : {},
    "created_at" : ISODate("2015-11-02T09:53:57.676Z"),
    "updated_at" : ISODate("2015-11-02T09:53:57.676Z")
}
```

Is it possible to populate the articles document with the actual categories documents and if yes, how would the syntax for this relationship look like?

P.S. What i am looking for is for eager loading. Execute a query on collection articles then another on the categories using $in : objectIDs

**Comment by superkhau** [comment]
I don't believe any of our connectors have join ATM. Escalating to feature request.

**Comment by mbouclas** [comment]
So, as far as Mongo goes, what is the practical use of relationships? Is it not to retrieve data from related models (collections)?

**Comment by jannyHou** [comment]
@mbouclas Actually we are doing this in `hasMany` and `hasManyThrough` relations. Please check document https://loopback.io/doc/en/lb3/HasMany-relations.html, and the api you are looking for would be an instance api `article.categories()`, or [`article.find({include: 'categories'})`](https://loopback.io/doc/en/lb2/Include-filter.html#examples)

I am closing this issue since it's too old, please feel free to open it if you have other questions. Thanks for understanding.
And for the feature "join", we keep all discussion in https://github.com/strongloop/loopback/issues/517
